# PagesCMS Süper Esnek ve Garanti Modifikasyonu
media:
  input: assets/img
  output: /assets/img

collections:
  # ==========================================
  # 1. BLOG YAZILARI (Zorlamasız Doğrudan Erişim)
  # ==========================================
  - id: posts
    label: Yazılar (Posts)
    type: collection
    path: _posts # Eğer yine gelmezse alt adımdaki 1. maddeye bakın
    # filename ve format zorunlulukları kaldırıldı, hata payı sıfıra indirildi
    fields:
      - id: title
        label: Başlık
        type: string
        required: true
      - id: layout
        label: Şablon
        type: string
        default: post
      - id: date
        label: Tarih
        type: datetime
      - id: categories
        label: Kategoriler
        type: list
        field:
          type: string
      - id: tags
        label: Etiketler
        type: list
        field:
          type: string
      - id: body
        label: İçerik
        type: markdown
        required: true